### ISSUE TITLE
Bug: publishing  does not work

### ISSUE THREAD

**Issue by lidel** [ipfs/awesome-ipfs#418]
Current publishing scripts use ancient Node 10 and old cluster scripts, which no longer work:

* https://app.circleci.com/pipelines/github/ipfs/awesome-ipfs/1071/workflows/46e19899-e038-406a-8ad1-ce0c92b7e41e/jobs/1762?invite=true#step-102-12

This means website updates are not published correctly.

We should fix publishing by switching to Fleek. 

## TODO

- [x] see if there is an easy (one-line) fix, if not, we need to migrate to Fleek
- [ ] remove old publishing scripts (based on olizilla/ipfs-dns-deploy)
- [x] add awesome.ipfs.io to Fleek
  - name it `awesome-ipfs`, this will give us DNSLink `/ipns/awesome-ipfs.on.fleek.co`
- [x] update DNS to point at Fleek
  - remove from collab cluster configs in https://github.com/protocol/bifrost-infra
   - add to managed domains in https://github.com/protocol/infra/ and set `awesome.ipfs.io` to point at Fleek CDN and DNSLink

**Comment by lidel** [comment]
@SgtPooki this is a good opportunity for you to learn how hosting websites on Fleek works

**Comment by SgtPooki** [comment]
I hosted pl-compass on fleek. <salesPitch>It's crazy easy.</salesPitch> I could handle this

**Comment by lidel** [comment]
I had to migrate to https://awesome.ipfs.tech (part of https://github.com/protocol/bifrost-infra/issues/178):
- the new domain is live, Fleek previews are enabled on PRs
- the old domain will be updated after https://github.com/protocol/infra/issues/908 is resolved
