### ISSUE TITLE
Awesome IPFS isn't awesome

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/awesome-ipfs#420]
### Todo

* Not a standard awesome list - and it should be (https://github.com/sindresorhus/awesome/blob/main/awesome.md)
   - [ ] We should remove outdated and otherwise un-awesome repos (https://github.com/sindresorhus/awesome/blob/main/awesome.md#only-awesome-is-awesome) 
   - [x] Include an awesome badge in our readme. (https://github.com/sindresorhus/awesome/blob/main/awesome.md#awesome-badge)
   - [ ] We are included in the root awesome repo and should include the "mentioned" badge and encourage those in our list to include a mention badge that links back to our repo. (https://github.com/sindresorhus/awesome/blob/main/awesome.md#awesome-mentioned-badge)
   - [ ] Ensure we include the reason why an item is included and that it makes sense (https://github.com/sindresorhus/awesome/blob/main/awesome.md#comment-on-why-something-is-awesome)
   - [ ] Audit the list description (https://github.com/sindresorhus/awesome/blob/main/awesome.md#make-it-clear-what-the-list-is-about)
   - [ ] Audit grammar (https://github.com/sindresorhus/awesome/blob/main/awesome.md#pay-attention-to-grammar)
   - [x] Use recommended license (https://github.com/sindresorhus/awesome/blob/main/awesome.md#choose-an-appropriate-license)
   - [ ] Audit contribution guidelines (https://github.com/sindresorhus/awesome/blob/main/awesome.md#include-contribution-guidelines)
   - [ ] Audit list style (https://github.com/sindresorhus/awesome/blob/main/awesome.md#stylize-your-list-properly)
   - [x] Continue to be awesome (https://github.com/sindresorhus/awesome/blob/main/awesome.md#accept-other-peoples-opinion)
* Awesome-ipfs should be consumed and then prettified on [explore.ipfs.io](https://ecosystem.ipfs.io/)* 

### Proposals

* We should attempt to automate everything we can 
   - [ ] Automatic PR creation to remove items that become out of date (older than X.. we need to define X)

**Comment by SgtPooki** [comment]
### Check links in readme

This could be added to a validator in a github action

```bash
cat README.md | awk '/\[([^\]]*)\]\(([^\)]*)\)/ { print $0 }' | perl -pe 's/.*\[([^\]]*)\]\(([^\)]*)\).*/$1 === $2/gm' | awk -F' === ' '{ print $2 }' | grep -v '^#' | xargs -tn1 -I% sh -c 'curl -s % > /dev/null || echo "% link is broken"'
```

**Comment by mark-bleep** [comment]
Came here to add something like this as well to the README:
Last Commit date would be a useful way to sort through these projects.

**Comment by SgtPooki** [comment]
> Last Commit date would be a useful way to sort through these projects

I agree that this would be useful, but I don't believe this is standard. Are there examples of any existing lists doing this?

**Comment by mark-bleep** [comment]
Not that I'm aware of.

It's the first thing I check in any repo, so if it's not part of the standard it should be.

-------- Original Message --------

**Comment by 2color** [comment]
There's a linter that can do the heavy lifting of checking the health of the links and making sure that the awesome list adheres to the format: 

https://github.com/sindresorhus/awesome-lint#github-actions

**Comment by SgtPooki** [comment]
> Not that I'm aware of. It's the first thing I check in any repo, so if it's not part of the standard it should be.

@mark-bleep I agree it would be useful, but if there are no readily available actions or other tools to keep that up to date then it's just something else for us to maintain that we unfortunately don't have time to do. 

I would be happy to merge a PR including a maintenance free method of achieving your idea.

**Comment by BigLep** [comment]
Related discussion: https://discuss.ipfs.io/t/rebooting-the-ipfs-awesome-list/14647/3

**Comment by SgtPooki** [comment]
Note to all that https://github.com/ipfs/awesome-ipfs/pull/429 is out and should improve the maintenance story significantly.

* Removed circleci (it was giving false negative results)
* Added cron job via github action that should also open PR removing invalid URLs (additional modifications will be needed on the opened PR)
* Added danger-js support that will fail the PR if links are invalid with messaging in a comment on the PR

**Comment by SgtPooki** [comment]
FYI that https://github.com/ipfs/awesome-ipfs/pull/434 implements a workflow that runs on a schedule (replacing circleci) that:

1. runs at 00:00 daily
2. automatically opens a PR that removes broken links from the data/* files (will need additional moderator changes to ensure yaml entry is fully removed)

Keeping this repo clean and up-to-date (at least as far as working links goes) will be much more simple moving forward! 🥳

**Comment by 2color** [comment]
Following the reboot (#478) of the list, hopefully we can continue working to iteratively work to make this list more awesome
